# Generated by Django 4.1.7 on 2023-04-02 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetodo',
            name='task',
        ),
        migrations.AddField(
            model_name='imagetodo',
            name='todo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_todo', to='task.todo'),
        ),
    ]
