# Generated by Django 4.1.7 on 2023-04-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_imagetodo_task_imagetodo_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetodo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
